version: '3.8'
services:
#  zookeeper:
#    image: bitnami/zookeeper:latest
#    ports:
#      - "2181:2181"
#    environment:
#      ALLOW_ANONYMOUS_LOGIN: 'yes'
#    networks:
#      - "mdlp2"


#  kafka:
#    image: bitnami/kafka:latest
#    ports:
#      - "9092:9092"
#    environment:
#      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
#      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
#      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: 'true'
#      ALLOW_PLAINTEXT_LISTENER: 'yes'
#    depends_on:
#      - zookeeper
#    networks:
#      - "mdlp2"
#
#  postgres:
#    image: "postgres"
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: password
#      POSTGRES_DB: exchange
#    ports:
#      - "5432:5432"
#    networks:
#      - "mdlp2"
#  rabbitmq:
#    image: "rabbitmq:3.11.3-alpine"
#    environment:
#      RABBITMQ_DEFAULT_USER: "rabbit"
#      RABBITMQ_DEFAULT_PASS: "rabbit"
#    restart: "always"
#    command: "rabbitmq-server"
#    healthcheck:
#      test: "rabbitmq-diagnostics -q ping"
#      interval: "5s"
#      timeout: "5s"
#      retries: 3
#    networks:
#      - "mdlp2"
#  redis:
#    image: "redis:7.0.5-alpine"
#    restart: "always"
#    networks:
#      - "mdlp2"
#    volumes:
#      - "./data:/data"
#    #ports:
#    #  - "6379:6379"
#    healthcheck:
#      test:
#        - "CMD"
#        - "redis-cli"
#        - "--raw"
#        - "incr"
#        - "ping"
#      interval: "5s"
#      timeout: "5s"
#      retries: 3
#    command: "--save 60 1 --loglevel warning --replica-read-only no"
#  ex1:
#    container_name: "ex1"
#    image: "alta.a-m0.ru/kafka_test:1.0.0"
#    #build:
#    #context: "../frame"
#    restart: "unless-stopped"
#    environment:
#      - "APP_DATABASE=dev.exchange.1" #имя БД -- можно изменить
#      - "APP_DB_HOST=postgres" #хост с БД - экземпляр сервиса postgres (см выше)
#      - "APP_DB_USER=web" #пользователь БД
#      - "APP_DB_PASSWORD=cdf90031-bfa4-4aa0" #пароль пользователя БД
#      - "APP_RABBIT_HOST=rabbitmq"
#      - "APP_RABBIT_PORT=5672"
#      - "APP_RABBIT_USER=rabbit"
#      - "APP_RABBIT_PASSWORD=rabbit"
#      - "DEBUG=kafka-node:*"
#      - "KAFKA_HOST=192.168.1.118:9092"
#    networks:
#      - "mdlp2"
#    ports:
#      - "8557:8001" #пробрасываемый порт
#    depends_on:
#      - "postgres"
#      - "redis"
#      - "rabbitmq"
#      - "kafka"
#networks:
#  mdlp2:
#    driver: "bridge"

#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    depends_on:
#      - kafka
#      - postgres
#    ports:
#      - "8080:8080"
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/exchange
#      SPRING_KAFKA_BOOTSTRAP-SERVERS: kafka:9092
#      # сюда добавить переменные при необходимости

