spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/exchange
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    consumer:
      properties:
        spring.json.trusted.packages: '*'
        spring.json.value.default.type: com.altasoft.exchange.message.MessageJson
        key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value.deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.kafka.consumer.value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
        spring.kafka.consumer.key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        spring.kafka.consumer.properties.spring.json.value.default.type: com.altasoft.exchange.message.MessageJson
        spring.kafka.consumer.properties.spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.kafka.consumer.properties.spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer